// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGBT7NQx8aJi1q2L4VCsyzon51kSIVr9Q',
    appId: '1:77406590329:web:1e3e4dcaa01dce4945cba8',
    messagingSenderId: '77406590329',
    projectId: 'tuan-a2941',
    authDomain: 'tuan-a2941.firebaseapp.com',
    storageBucket: 'tuan-a2941.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_BZ5sIKvMT5GC6wQFLFVaU0yHXU43-iw',
    appId: '1:77406590329:android:0608d22ca996cb5545cba8',
    messagingSenderId: '77406590329',
    projectId: 'tuan-a2941',
    storageBucket: 'tuan-a2941.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6EA0qrqQkHxMJllWP31RE4kRi0hLES-Q',
    appId: '1:77406590329:ios:fda5c88a23392cf245cba8',
    messagingSenderId: '77406590329',
    projectId: 'tuan-a2941',
    storageBucket: 'tuan-a2941.firebasestorage.app',
    iosBundleId: 'com.example.tuanHung',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6EA0qrqQkHxMJllWP31RE4kRi0hLES-Q',
    appId: '1:77406590329:ios:fda5c88a23392cf245cba8',
    messagingSenderId: '77406590329',
    projectId: 'tuan-a2941',
    storageBucket: 'tuan-a2941.firebasestorage.app',
    iosBundleId: 'com.example.tuanHung',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBGBT7NQx8aJi1q2L4VCsyzon51kSIVr9Q',
    appId: '1:77406590329:web:ced0f478a0d23dad45cba8',
    messagingSenderId: '77406590329',
    projectId: 'tuan-a2941',
    authDomain: 'tuan-a2941.firebaseapp.com',
    storageBucket: 'tuan-a2941.firebasestorage.app',
  );
}
